### ISSUE TITLE
Missing individual Daily and Total Production channels on openHAB 4.3.0.M2 for (Deye-SUN-2000G3-EU - deye_4mppt)

### ISSUE THREAD

**Issue by bolausson** [catalinsanda/org.openhab.binding.solarman#37]
Hello,

I am on openHAB 4.3.0.M2 and the solarman logger is back in a working state for Deye-SUN-2000G3-EU (deye_4mppt) with firmware MW3_SSL_5408_1.0B.

I am missing some counters (channels) though for the plugin which is distributed via the openHAB "store".
Not sure if this is the right place to report this or if I should report it on the openHAB repo.

Before the last update (https://github.com/catalinsanda/org.openhab.binding.solarman/pull/36) there were was the "Total Production" and the "Total Production for each of the four panels" - now there is only the "Total Production" reported. Likewise for the "Daily Production"

I only have **two** solar pannels connected (just in case someone is wondering why there is only data for panel 1 and 2).

![image](https://github.com/user-attachments/assets/ec64fc30-8cb1-4cda-8601-e88a7b9ad311)
![image](https://github.com/user-attachments/assets/e06e13d9-9bde-4c0a-bc1b-2790a942ae77)

Before:
![image](https://github.com/user-attachments/assets/9a3be50c-133e-4842-bdc9-6faa8a1ceee5)

After:
![image](https://github.com/user-attachments/assets/bf318192-db96-451c-acbf-0947a953ac1b)

Greetings,
Bjoern

**Comment by catalinsanda** [comment]
Hi Bjoern,

Yes, you're right. The new version of [deye_4mppt.yaml](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml) is missing individual power per input like the [old](https://github.com/openhab/openhab-addons/blob/1cd7a4fd4bd97286566eb6882c1587472474261e/bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml) one did.
I don't know why the upstream project [home_assistant_solarman](https://github.com/StephanJoubert/home_assistant_solarman) I get them from has decided to remove them. At the next update I'll try to add them back in.

In the meantime you can use the `additionalRequests` support to fetch them, even though they're not in the definitions. In your case you don't seem to need additional modbus requests as the whole range is being fetched, just the channels.

It should look something like this (I haven't tested as I don't have the inverter):
```
Thing solarman:logger:local [ hostname="x.x.x.x", inverterType="deye_sg04lp3", serialNumber="1234567890"] {
        Channels:
            Type number : daily_production_1 [scale="0.1", uom="kWh", rule="1", registers="0x0041"]
            Type number : daily_production_2 [scale="0.1", uom="kWh", rule="1", registers="0x0042"]
            Type number : daily_production_3 [scale="0.1", uom="kWh", rule="1", registers="0x0043"]
            Type number : daily_production_4 [scale="0.1", uom="kWh", rule="1", registers="0x0044"]
}
```
If you need other pieces of info from the old definition, just add them to the list of channels like above.

Hope this helps,
Catalin

**Comment by bolausson** [comment]
Thanks a lot!

Should we keep this issue open until it was resolved for the "official" Add-On?

**Comment by catalinsanda** [comment]
Didn't get a chance to update them, and to be honest I'm a bit reluctant to have them diverge from upstream, as it will make further integrations more difficult. 
Please use the solution I mentioned above and you should be good to go.

**Comment by bolausson** [comment]
ok

**Comment by catalinsanda** [comment]
That goes into the things file for your Solarman thing. Based on your question, I assume you don't use thing / item files to configure OpenHAB, but instead you do it via the UI, 
In that case you add new channels by clicking the "Add Channel" button:
![image](https://github.com/user-attachments/assets/8aded5b4-b8ec-43e2-95e1-48b2959b485c)
but in my case it gets stuck in an infinite loading:
![image](https://github.com/user-attachments/assets/12e681d2-5558-4b6f-beb7-ed7afcba4b73)
Can you please check if the same happens to you?

**Comment by bolausson** [comment]
Correct, I configured everything via the WebUI.

Unfortunately I get the same infinite loading:
![image](https://github.com/user-attachments/assets/8da58553-bead-4dd5-870a-51eb0a3b06bb)

There is no other thing available where I could try to "Add Channel" to see if this is behaviour is exclusive to the Solarman binding or a general issue.

I tried to replicate the code block but my edits are not saved:
![image](https://github.com/user-attachments/assets/2c38c2a0-e060-4fb6-8551-130843e63e3e)
When I hit "Save" the UI says "Thing updated" but when I go back and re-open the thing, the code block is gone.

I guess there is not "third" option to get around this :-)

**Comment by catalinsanda** [comment]
The issue seems to be with the binding. More precisely the integration of the binding with the OpenHAB channel discovery mechanism. 

I did a quick investigation and when trying to add a new channel, the UI tries to request the channel type `solarman:true`, which doesn't exist, so the back-end returns a 204, and the UI is stuck in that loop.

I will need to investigate why is called with `solarman:true` and if that's expected, what's the correct response to it. But I'll be out of town next week, so expect some delays.

Now, that this binding has been merged and released with OpenHAB 4.3, can you please open a bug in the OpenHAB repo?

**Comment by bolausson** [comment]
Thank!

I opened a bug as requests:
https://github.com/openhab/openhab-addons/issues/17959

**Comment by catalinsanda** [comment]
@bolausson - I fixed the problem, it had nothing to do with HTTP2, it was a misunderstanding on my part on how OpenHAB reads channels types.

I'll open a PR against the addons repo with the fix and reference your issue.

![image](https://github.com/user-attachments/assets/4a279358-71dc-4450-b1c1-b30e748998e4)

**Comment by bolausson** [comment]
Thanks!

**Comment by catalinsanda** [comment]
@bolausson - the bug fix has been merged in OpenHAB 4.3.2, which is out. Can you please validate that you can add new channels and you get the data that you want?

**Comment by bolausson** [comment]
Thanks for the reminder!

I was able to add the channels:
![Image](https://github.com/user-attachments/assets/4dc58641-edee-4c6c-8e76-6d468f407f64)

Two things I wonder about:

- For the individual "total production", the [original definition](https://github.com/openhab/openhab-addons/blob/1cd7a4fd4bd97286566eb6882c1587472474261e/bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml) contained a state_class "total_increasing" which is missing in the "Add channel" configuration WebUI dialog - not sure if this is needed though.
- For the individual "Daily Production" channels, the [original definition](https://github.com/openhab/openhab-addons/blob/1cd7a4fd4bd97286566eb6882c1587472474261e/bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml) contained a state_class "total" which is missing as well - again, I don't know if this is relevant.

![Image](https://github.com/user-attachments/assets/a689d29d-c064-45e9-936b-b2d01900ca01)

Code after adding the channels via the WebUI:
```
UID: solarman:logger:XYZ
label: Deye-SUN-2000G3-EU
thingTypeUID: solarman:logger
configuration:
  inverterType: deye_4mppt
  hostname: 10.0.1.170
  serialNumber: "0123456789"
  solarmanLoggerMode: V5MODBUS
  port: 8899
  refreshInterval: 60
location: Balkon
channels:
  - id: solar-daily-production-pv1
    channelTypeUID: solarman:number
    label: Daily Production 1
    description: ""
    configuration:
      rule: 1
      scale: 0.1
      registers: "[0x0041]"
      uom: kWh
  - id: solar-daily-production-pv2
    channelTypeUID: solarman:number
    label: Daily Production 2
    description: ""
    configuration:
      rule: 1
      scale: 0.1
      registers: "[0x0042]"
      uom: kWh
  - id: solar-daily-production-pv3
    channelTypeUID: solarman:number
    label: Daily Production 3
    description: ""
    configuration:
      rule: 1
      scale: 0.1
      registers: "[0x0043]"
      uom: kWh
  - id: solar-daily-production-pv4
    channelTypeUID: solarman:number
    label: Daily Production 4
    description: ""
    configuration:
      rule: 1
      scale: 0.1
      registers: "[0x0044]"
      uom: kWh
  - id: solar-total-production-pv1
    channelTypeUID: solarman:number
    label: Total Production 1
    description: ""
    configuration:
      rule: 3
      scale: 0.1
      registers: "[0x0045]"
      uom: kWh
  - id: solar-total-production-pv2
    channelTypeUID: solarman:number
    label: Total Production 2
    description: ""
    configuration:
      rule: 3
      scale: 0.1
      registers: "[0x0047]"
      uom: kWh
  - id: solar-total-production-pv3
    channelTypeUID: solarman:number
    label: Total Production 3
    description: ""
    configuration:
      rule: 3
      scale: 0.1
      registers: "[0x0046]"
      uom: kWh
  - id: solar-total-production-pv4
    channelTypeUID: solarman:number
    label: Total Production 4
    description: ""
    configuration:
      rule: 3
      scale: 0.1
      registers: "[0x0048]"
      uom: kWh
  - id: solar-pv1-voltage
    channelTypeUID: solarman:deye-4mppt-solar-pv1-voltage
    label: PV1 Voltage
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x006D]"
      uom: V
      offset: 0
  - id: inverter-restore-factory-settings
    channelTypeUID: solarman:deye-4mppt-inverter-restore-factory-settings
    label: Restore Factory Settings
    configuration:
      scale: 1
      rule: 5
      registers: "[0x0036]"
      uom: ""
      offset: 0
  - id: inverter-inverter-id
    channelTypeUID: solarman:deye-4mppt-inverter-inverter-id
    label: Inverter ID
    configuration:
      scale: 1
      rule: 5
      registers: "[0x0003,0x0004,0x0005,0x0006,0x0007]"
      uom: ""
      offset: 0
  - id: solar-pv2-voltage
    channelTypeUID: solarman:deye-4mppt-solar-pv2-voltage
    label: PV2 Voltage
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x006F]"
      uom: V
      offset: 0
  - id: solar-pv1-current
    channelTypeUID: solarman:deye-4mppt-solar-pv1-current
    label: PV1 Current
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x006E]"
      uom: A
      offset: 0
  - id: solar-active-power-regulations
    channelTypeUID: solarman:deye-4mppt-solar-active-power-regulations
    label: Active Power Regulations
    configuration:
      scale: 1
      rule: 1
      registers: "[0x0028]"
      uom: "%"
      offset: 0
  - id: solar-pv4-current
    channelTypeUID: solarman:deye-4mppt-solar-pv4-current
    label: PV4 Current
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0074]"
      uom: A
      offset: 0
  - id: solar-daily-production
    channelTypeUID: solarman:deye-4mppt-solar-daily-production
    label: Daily Production
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x003C]"
      uom: kWh
      offset: 0
  - id: inverter-soft-start-enable
    channelTypeUID: solarman:deye-4mppt-inverter-soft-start-enable
    label: Soft Start Enable
    configuration:
      scale: 1
      rule: 5
      registers: "[0x002F]"
      uom: ""
      offset: 0
  - id: inverter-rated-power
    channelTypeUID: solarman:deye-4mppt-inverter-rated-power
    label: Rated Power
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0010]"
      uom: W
      offset: 0
  - id: solar-pv3-current
    channelTypeUID: solarman:deye-4mppt-solar-pv3-current
    label: PV3 Current
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0072]"
      uom: A
      offset: 0
  - id: solar-pv2-current
    channelTypeUID: solarman:deye-4mppt-solar-pv2-current
    label: PV2 Current
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0070]"
      uom: A
      offset: 0
  - id: grid-ac-output-frequency
    channelTypeUID: solarman:deye-4mppt-grid-ac-output-frequency
    label: AC Output Frequency
    configuration:
      scale: 0.01
      rule: 1
      registers: "[0x004F]"
      uom: Hz
      offset: 0
  - id: inverter-total-ac-output-power--active-
    channelTypeUID: solarman:deye-4mppt-inverter-total-ac-output-power--active-
    label: Total AC Output Power (Active)
    configuration:
      scale: 0.1
      rule: 3
      registers: "[0x0056,0x0057]"
      uom: W
      offset: 0
  - id: solar-pv4-voltage
    channelTypeUID: solarman:deye-4mppt-solar-pv4-voltage
    label: PV4 Voltage
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0073]"
      uom: V
      offset: 0
  - id: inverter-radiator-temperature
    channelTypeUID: solarman:deye-4mppt-inverter-radiator-temperature
    label: Radiator Temperature
    configuration:
      scale: 0.01
      rule: 1
      registers: "[0x005A]"
      uom: °C
      offset: 1000
  - id: solar-total-production
    channelTypeUID: solarman:deye-4mppt-solar-total-production
    label: Total Production
    configuration:
      scale: 0.1
      rule: 3
      registers: "[0x003F,0x0040]"
      uom: kWh
      offset: 0
  - id: inverter-start-up-self-checking-time
    channelTypeUID: solarman:deye-4mppt-inverter-start-up-self-checking-time
    label: "Start-up Self-checking Time "
    configuration:
      scale: 1
      rule: 1
      registers: "[0x0015]"
      uom: s
      offset: 0
  - id: solar-pv3-voltage
    channelTypeUID: solarman:deye-4mppt-solar-pv3-voltage
    label: PV3 Voltage
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0071]"
      uom: V
      offset: 0
  - id: inverter-power-factor-regulation
    channelTypeUID: solarman:deye-4mppt-inverter-power-factor-regulation
    label: Power Factor Regulation
    configuration:
      scale: 0.1
      rule: 2
      registers: "[0x0032]"
      uom: ""
      offset: 0
  - id: grid-ac-voltage
    channelTypeUID: solarman:deye-4mppt-grid-ac-voltage
    label: AC Voltage
    configuration:
      scale: 0.1
      rule: 1
      registers: "[0x0049]"
      uom: V
      offset: 0
  - id: grid-grid-current
    channelTypeUID: solarman:deye-4mppt-grid-grid-current
    label: Grid Current
    configuration:
      scale: 0.1
      rule: 2
      registers: "[0x004C]"
      uom: A
      offset: 0
  - id: inverter-running-status
    channelTypeUID: solarman:deye-4mppt-inverter-running-status
    label: Running Status
    configuration:
      scale: 1
      rule: 5
      registers: "[0x003B]"
      uom: ""
      offset: 0
```
